### ISSUE TITLE
Remove IDENTITY_COMPOSE permission

### ISSUE THREAD

**Issue by msporny** [digitalbazaar/bedrock-website-user-http#2]
The IDENTITY_COMPOSE permission is included in bedrock-website-user-http:

https://github.com/digitalbazaar/bedrock-website-user-http/blob/master/lib/config.js#L32

... but it is defined in a module that may not be used by bedrock-related software:

https://github.com/digitalbazaar/bedrock-credentials-mongodb/blob/8f083c712d0399fdce8e92f3e92d60c2f3a1399c/lib/config.js#L46

This is certainly the case for Aseta's software. IDENTITY_COMPOSE shouldn't be included in the core identity permission set for registered identities. Instead, it should be added to the default registered identity by bedrock-credentials-rest or a similar credentials-based library.

**Comment by dlongley** [comment]
> Instead, it should be added to the default registered identity by bedrock-credentials-rest or a similar credentials-based library.

I agree we should remove it from this module, but I disagree with adding it to any library that is essentially middleware. It should be added to a similar package to this one that is for credential-based systems.

**Comment by mattcollier** [comment]
Fixed via https://github.com/digitalbazaar/bedrock-website-user-http/commit/5c1f14be85f2d51fdfec030e1d257ecbdc27ac14
